<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="bison">

    <!-- PARAMETRES -->
    <xacro:property name="base_length" value="1.08" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.37" />
    <xacro:property name="base_mass" value="2.0" />
    <xacro:property name="wheel_radius" value="0.15" />
    <xacro:property name="wheel_length" value="0.19" />
    <xacro:property name="wheel_mass" value="0.2" />
    <xacro:property name="wheel_position_X" value="0.34" />
    <xacro:property name="wheel_position_Z" value="0.055" />

    <!-- MATERIAUX -->
    <material name="gray">
        <color rgba="0.2 0.2 0.2 1.0"/>
    </material>

    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>

    <material name="light_gray">
        <color rgba="0.6 0.6 0.6 1.0"/>
    </material>

    <material name="light_blue">
        <color rgba="0.1 0.1 0.9 1.0"/>
    </material>

    <material name="yellow">
        <color rgba="0 1 0 1"/>
    </material>

    <!-- MACROS -->
    <xacro:macro name="box_inertial" params="mass l w h">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="${mass/3*(w*w + h*h)}" ixy="${mass/4*l*w}" ixz="${mass/4*l*h}" iyy="${mass/3*(l*l + h*h)}" iyz="${mass/4*w*h}" izz="${mass/3*(l*l + w*w)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertial" params="mass r h">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="${mass/12*(3*r*r + h*h)}" ixy="0.0" ixz="0.0" iyy="${mass/12*(3*r*r + h*h)}" iyz="0.0" izz="${mass/2*(r*r)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="spherus_inertial" params="mass r">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="${mass/5*2*(r*r)}" ixy="0.0" ixz="0.0" iyy="${mass/5*2*(r*r)}" iyz="0.0" izz="${mass/5*2*(r*r)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="wheel_origin" params="side">
        <xacro:if value="${side == 'left'}">
            <origin xyz="0.0 ${-wheel_length/2} 0.0" rpy="${pi/2} 0.0 0.0"/>
        </xacro:if>
        <xacro:if value="${side == 'right'}">
            <origin xyz="0.0 ${wheel_length/2} 0.0" rpy="${pi/2} 0.0 0.0"/>
        </xacro:if>
    </xacro:macro>

    <xacro:macro name="wheel_joint_origin" params="side">
        <xacro:if value="${side == 'left'}">
            <origin xyz="${wheel_position_X} ${-base_width/2} ${wheel_position_Z}" />
        </xacro:if>
        <xacro:if value="${side == 'right'}">
            <origin xyz="${wheel_position_X} ${base_width/2} ${wheel_position_Z}" />
        </xacro:if>
    </xacro:macro>

    <xacro:macro name="wheel_joint_origin_back" params="side">
        <xacro:if value="${side == 'left'}">
            <origin xyz="${-wheel_position_X} ${-base_width/2} ${wheel_position_Z}" />
        </xacro:if>
        <xacro:if value="${side == 'right'}">
            <origin xyz="${-wheel_position_X} ${base_width/2} ${wheel_position_Z}" />
        </xacro:if>
    </xacro:macro>

    <xacro:macro name="wheel_macro" params="side *shape">
        <link name="${side}_wheel">
            <visual>
                <geometry>
                    <xacro:insert_block name="shape" />
                </geometry>
                <xacro:wheel_origin side="${side}" />
                <material name="black"/>
            </visual>
            <collision>
                <geometry>
                    <xacro:insert_block name="shape" />
                </geometry>
                <xacro:wheel_origin side="${side}" />
            </collision>
            <xacro:cylinder_inertial mass="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}"/>
        </link>

        <joint name="${side}_wheel_joint" type="continuous">
            <xacro:wheel_joint_origin side="${side}" />
            <parent link="base_link"/>
            <child link="${side}_wheel"/>
            <axis xyz="0 1 0" />
        </joint>


    </xacro:macro>

    <xacro:macro name="wheel_macro_back" params="side *shape">
        <link name="${side}_wheel_back">
            <visual>
                <geometry>
                    <xacro:insert_block name="shape" />
                </geometry>
                <xacro:wheel_origin side="${side}" />
                <material name="yellow"/>
            </visual>
            <collision>
                <geometry>
                    <xacro:insert_block name="shape" />
                </geometry>
                <xacro:wheel_origin side="${side}" />
            </collision>
            <xacro:cylinder_inertial mass="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}"/>
        </link>

        <joint name="${side}_wheel_joint_back" type="continuous">
            <xacro:wheel_joint_origin_back side="${side}" />
            <parent link="base_link"/>
            <child link="${side}_wheel_back"/>
            <axis xyz="0 1 0" />
        </joint>


    </xacro:macro>


    <!-- LINKS et JOINTS -->

    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>

            </geometry>
            <origin xyz="0.0 0.0 ${base_height/2}"/>
            <material name="light_blue"/>
        </visual>

        <xacro:box_inertial mass="${base_mass}" l="${base_length}" w="${base_width}" h="${base_height}"/>

    </link>

    <joint name="base_link_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
    </joint>

    <xacro:wheel_macro side="left">
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
    </xacro:wheel_macro>

    <xacro:wheel_macro side="right">
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
    </xacro:wheel_macro>

    <xacro:wheel_macro_back side="left">
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
    </xacro:wheel_macro_back>

    <xacro:wheel_macro_back side="right">
        <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
    </xacro:wheel_macro_back>


</robot>
